repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1  # Use latest version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use latest version
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use latest version
    hooks:
      - id: flake8
